#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 20-esphome

check_container_initialized
check_service_initialized init

if [ -z "${ESPHOME_USERNAME}" ] && [ -n "${ADMIN_USER}" ]; then
    export ESPHOME_USERNAME="${ADMIN_USER}"
fi
if [ -z "${ESPHOME_PASSWORD}" ] && [ -n "${ADMIN_PASS}" ]; then
    export ESPHOME_PASSWORD="${ADMIN_PASS}"
fi

case "${LOG_TYPE,,}" in
    both )
        SHOW_OUTPUT=TRUE
        touch "${LOG_PATH}"/"${LOG_FILE}"
        chown -R "${ESPHOME_USER}" "${LOG_PATH}"/"${LOG_FILE}"
    ;;
    console )
        SHOW_OUTPUT=TRUE
        LOG_PATH=/dev
        LOG_FILE=/null
    ;;
    file )
        SHOW_OUTPUT=FALSE
        touch "${LOG_PATH}"/"${LOG_FILE}"
        chown -R "${ESPHOME_USER}" "${LOG_PATH}"/"${LOG_FILE}"
    ;;
    none )
        SHOW_OUTPUT=FALSE
        LOG_PATH=/dev
        LOG_FILE=null
    ;;
esac

liftoff

print_start "Starting ESPHome ${ESPHOME_VERSION}"
source /opt/esphome/bin/activate
export HOME=${CACHE_PATH%/}
exec s6-setuidgid "${ESPHOME_USER}" \
                                            /opt/esphome/bin/esphome-device-builder \
                                            --host "${LISTEN_IP}" \
                                            --port "${LISTEN_PORT}" \
                                            "${CONFIG_PATH}"
