#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 20-esphome

esphome_bootstrap_filesystem
esphome_configure_cache
esphome_configure_logging
esphome_configure_proxy
esphome_configure_settings

liftoff
