services:

  esphome-app:
    image: docker.io/nfrastack/esphome
    container_name: esphome-app
    ports:
      - 6052:6052
    volumes:
      - ./cache:/cache
      - ./config:/config
      - ./logs:/logs
    environment:
      - TIMEZONE=America/Vancouver
      - ENABLE_NGINX=FALSE
      - ADMIN_USER=esphome
      - ADMIN_PASS=nfrastack
    networks:
      - services
    restart: always

networks:
  services:
    external: true
